### ISSUE TITLE
Crashed "Scaling Feast, Apple Core"

### ISSUE THREAD

**Issue by Scarlette564** [Heaveness/RotN-BPG-Edition#1]
Crashed while eating blubber, not really sure what happened so I'm gonna upload the crash report.
[crash-2020-07-15_17.04.47-server.txt](https://github.com/Heaveness/RotN-BPG-Edition/files/4928001/crash-2020-07-15_17.04.47-server.txt)

Thanks!

**Comment by Heaveness** [comment]
This is a known issue with scaling feast when it comes to eating certain food or it handles certain events during eating. This one is going to be very difficult to fix. I will see what I can do, but can't guarantee anything.

**Comment by yeelp** [comment]
Found this through RotN discord (Which I'm a part of).

If I was aware Scaling Feast was a part of BPG, I probably would've followed BPG's development a little more closely to help ensure Scaling Feast runs nicely with everything else. Sorry about that! @Heaveness, you could've (and maybe should've) posted and linked this issue on Scaling Feast's GitHub about this to help bring it to my attention since this is a completely new issue.

Actually... I'm looking at the crash report, and you're using Scaling Feast 1.2.6-beta?! The latest version is 1.5.1. It's likely this problem can be fixed by using the most recent version of Scaling Feast, however I'm more than happy to look into this if the problem persists, along with any other Scaling Feast related issues, should they exist; just post an issue on Scaling Feast's GitHub or just @ me on the RotN Discord, if that's somehow more convenient.

**Comment by Heaveness** [comment]
Hey thanks yeelp. I didn't realized it was using an old one, I will most likely update it for 1.0.4 content update.
